---
seed_everything: 42

model:
  class_path: model.LitDP
  init_args:
    states_seq_len: 4
    action_generate_len: 16
    action_seq_len: 4
    unet_config:
      condition_dim: 50
      action_dim: 2
      kernel_size: 3
      n_groups: 8
      down_dims: [32, 64, 128]
      diffusion_step_embed_dim: 128
    noise_scheduler_config:
      num_train_timesteps: 100
      num_inference_steps: 100
      beta_schedule: squaredcos_cap_v2
      beta_start: 0.0001
      beta_end: 0.02
      clip_sample: True
      clip_sample_range: 1.0


optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001

trainer:
  accelerator: gpu
  max_epochs: -1
  gradient_clip_val: 10
  precision: 16-mixed
  log_every_n_steps: 1
  logger:
    class_path: WandbLogger
    init_args:
      log_model: false
      project: dp-test
      save_dir: .venv
  callbacks:
    -
      class_path: EarlyStopping
      init_args:
        monitor: val_loss
        patience: 200
        mode: min
        verbose: True

data:
  class_path: dataset.CircleDataModule
  init_args:
    train_size: 16
    val_size: 4
    num_points: 50
    batch_size: 8
    window_size: 16
