name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync
      - name: Run lint
        run: |
          uv run ruff check .
          uv run mypy --strict src/
      - name: Run tests
        run: |
          uv run pytest -ra --doctest-modules --cov=src --cov-report=term --cov-report=xml
